/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_BQ4050_PB_H_INCLUDED
#define PB_BQ4050_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _test { 
    int32_t n; 
} test;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define test_init_default                        {0}
#define test_init_zero                           {0}

/* Field tags (for use in manual encoding/decoding) */
#define test_n_tag                               1

/* Struct field encoding specification for nanopb */
#define test_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    n,                 1)
#define test_CALLBACK NULL
#define test_DEFAULT NULL

extern const pb_msgdesc_t test_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define test_fields &test_msg

/* Maximum encoded size of messages (where known) */
#define test_size                                11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
